In [ ]:
# I will create a DataFrame with the following columns: Name, Age, City, Income Include at least two
# missing values (e.g., None or NaN). 2. Check which values are missing. 3. Fill missing ages with
# the average age. 4. Fill missing income with 0. 5. Create a new column: Income_Level = "High"
# if Income > 60000 else "Low" 6. Display only the rows where Income_Level is "High".

import pandas as pd
import numpy as np

# 1. Create DataFrame with missing values
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, np.nan, 30, 35, np.nan],
    'City': ['New York', 'London', 'Paris', 'Tokyo', 'Sydney'],
    'Income': [70000, 50000, np.nan, 80000, np.nan]
}
df = pd.DataFrame(data)

# 2. Check which values are missing
print("Missing values per column:\n", df.isnull().sum())

# 3. Fill missing ages with the average age
df['Age'] = df['Age'].fillna(df['Age'].mean())

# 4. Fill missing income with 0
df['Income'] = df['Income'].fillna(0)

# 5. Create Income_Level column
df['Income_Level'] = df['Income'].apply(lambda x: 'High' if x > 60000 else 'Low')

# 6. Display only "High" income rows
high_income_df = df[df['Income_Level'] == 'High']
print("\nHigh Income Rows:\n", high_income_df)

Missing values per column:
 Name      0
Age       2
City      0
Income    2
dtype: int64

High Income Rows:
     Name   Age      City   Income Income_Level
0  Alice  25.0  New York  70000.0         High
3  David  35.0     Tokyo  80000.0         High

In [66]:
# Create a DataFrame with: Product, Category, Price, Quantity 2. Compute a new column:
# Total_Value =Price * Quantity 3. Group by Category and compute: o Total quantity sold o Average
# price o Total value 4. Sort categories by Total_Value in descending order. 5. Display the top-
# earning category.

# 1. Create DataFrame
sales_data = {
    'Product': ['Laptop', 'Mouse', 'Monitor', 'Keyboard', 'Laptop', 'Monitor'],
    'Category': ['Electronics', 'Peripherals', 'Electronics', 'Peripherals', 'Electronics', 'Electronics'],
    'Price': [1200, 25, 300, 75, 1200, 300],
    'Quantity': [5, 20, 10, 15, 3, 7]
}
df_sales = pd.DataFrame(sales_data)

# 2. Compute Total_Value column
df_sales['Total_Value'] = df_sales['Price'] * df_sales['Quantity']

# 3. Group by Category and compute metrics
category_summary = df_sales.groupby('Category').agg(
    Total_Quantity=('Quantity', 'sum'),
    Average_Price=('Price', 'mean'),
    Total_Value=('Total_Value', 'sum')
)

# 4. Sort categories by Total_Value in descending order
category_summary = category_summary.sort_values(by='Total_Value', ascending=False)

# 5. Display the top-earning category
print("Category Summary:\n", category_summary)
print("\nTop Earning Category:", category_summary.index[0])

Category Summary:
              Total_Quantity  Average_Price  Total_Value
Category
Electronics              25          750.0        14700
Peripherals              35           50.0         1625

Top Earning Category: Electronics

In [ ]:
# Category Level Sales Analysis (Working with pandas data structure)


# 1) Group by Product and calculate total units sold and revenue
product_summary = df_sales.groupby("Product").agg(
    Total_Units=("Quantity", "sum"),
    Total_Revenue=("Total_Value", "sum")
).reset_index()

print("Product Summary:")
display(product_summary)

# 2) Sort products by revenue (highest first)
product_sorted = product_summary.sort_values("Total_Revenue", ascending=False)

print("Products sorted by revenue:")
display(product_sorted)

# 3) Identify the top selling product
top_product = product_sorted.iloc[0]

print(f"Top selling product: {top_product['Product']}")
print(f"Total revenue generated: ${top_product['Total_Revenue']}")

Product Summary:

    Product  Total_Units  Total_Revenue
0  Keyboard           15           1125
1    Laptop            8           9600
2   Monitor           17           5100
3     Mouse           20            500

Products sorted by revenue:

    Product  Total_Units  Total_Revenue
1    Laptop            8           9600
2   Monitor           17           5100
0  Keyboard           15           1125
3     Mouse           20            500

Top selling product: Laptop
Total revenue generated: $9600

- What we have here is a deeper analysis to the previous code completed above using GroupBy

- The product generating the highest revenue is Laptop ($9600).

- Sorting the products helps identify the best performing items.

- Even though Mouse sold the most units, it generated the lowest revenue, showing that price strongly affects revenue.

In [ ]:
# Grouping, Aggregation and Sorting (Jupyter Notebook: Woking with Pandas Exercise THURSDAY).

# Group by Product and calculate total units sold and total revenue
product_summary = df_sales.groupby("Product").agg(
    Total_Units=("Quantity", "sum"),
    Total_Revenue=("Total_Value", "sum")
).reset_index()

print("Product Summary:")
display(product_summary)

Product Summary:

    Product  Total_Units  Total_Revenue
0  Keyboard           15           1125
1    Laptop            8           9600
2   Monitor           17           5100
3     Mouse           20            500

In [69]:
# Sort products by total revenue
product_sorted = product_summary.sort_values("Total_Revenue", ascending=False)

print("Products sorted by revenue:")
display(product_sorted)

# Identify the top selling product
top_product = product_sorted.iloc[0]

print(f"Top selling product: {top_product['Product']}")
print(f"Total revenue generated: ${top_product['Total_Revenue']}")

Products sorted by revenue:

    Product  Total_Units  Total_Revenue
1    Laptop            8           9600
2   Monitor           17           5100
0  Keyboard           15           1125
3     Mouse           20            500

Top selling product: Laptop
Total revenue generated: $9600

### Insights

- After grouping and sorting the data, we can clearly see which products contribute the most to total revenue.
- Although some products may sell more units, higher-priced products can generate more revenue overall.  
- Identifying the top-performing products helps businesses focus on items that drive the most value.

In [ ]:
# JSON file (following the cleaning process for it).

data = {
    "name": ["Luka", "Mike", "Jacob", "Ja", "Lou"],
    "age": [19, 25, 43, 32, 18],
    "city": ["Los Angeles", "San Diego", "Edmonton", "New York", "Toronto"],
    "income": [52000, 63000, 44000, 90000, 55000],
}

df = pd.DataFrame(data)

print("Original DataFrame:")
display(df)

# Convert DataFrame to JSON format
json_data = df.to_json(orient="records")

print("JSON format:")
print(json_data)

Original DataFrame:

    name  age         city  income
0   Luka   19  Los Angeles   52000
1   Mike   25    San Diego   63000
2  Jacob   43     Edmonton   44000
3     Ja   32     New York   90000
4    Lou   18      Toronto   55000

JSON format:
[{"name":"Luka","age":19,"city":"Los Angeles","income":52000},{"name":"Mike","age":25,"city":"San Diego","income":63000},{"name":"Jacob","age":43,"city":"Edmonton","income":44000},{"name":"Ja","age":32,"city":"New York","income":90000},{"name":"Lou","age":18,"city":"Toronto","income":55000}]

In [71]:
# After we loaded the JSON back into a DataFrame, we can perform some quick insights and sorting based on the income column.

# Simple insights
print("Average income:", df_json["income"].mean())
print("Highest income:", df_json["income"].max())

# Sort by income
sorted_income = df_json.sort_values("income", ascending=False)

# And the results are as follows:
print("People sorted by income:")
display(sorted_income)

Average income: 60800.0
Highest income: 90000
People sorted by income:

    name  age         city  income
3     Ja   32     New York   90000
1   Mike   25    San Diego   63000
4    Lou   18      Toronto   55000
0   Luka   19  Los Angeles   52000
2  Jacob   43     Edmonton   44000

- The dataset was converted from a Pandas DataFrame to JSON format and then back into a DataFrame.

- The highest income in the dataset is $90,000 (Ja).

- Sorting by income shows the distribution of earnings among individuals.

In [ ]:
# Working with Messy Text files in Pandas (Student Exercise).

# Working with messy data

# List the messy data
messy_text = """
community | participants | avg_age | device_access | notes
Kijiji | 23 | 31 | mobile phones | ; tablets | inconsistant attendance 
Makondo|17| | mobile phones| missing age data
Luwero | 45|29 mobile phones ; laptops | 
Gulu| | 34 | tablets | device count unclear 
Mbale | 38 | 28| mobile phones ; laptops; tablets | good engagement
"""
print("Messy Text Data:\n", messy_text)

Messy Text Data:

community | participants | avg_age | device_access | notes
Kijiji | 23 | 31 | mobile phones | ; tablets | inconsistant attendance
Makondo|17| | mobile phones| missing age data
Luwero | 45|29 mobile phones ; laptops |
Gulu| | 34 | tablets | device count unclear
Mbale | 38 | 28| mobile phones ; laptops; tablets | good engagement

In [73]:
# Load messy data text file
import pandas as pd
from io import StringIO
df_raw = pd.read_csv(
    StringIO(messy_text),
    sep="\\|",
    engine="python",
    skip_blank_lines=True
)
df_raw

,community,participants,avg_age,device_access,notes
Kijiji,23,31,mobile phones,; tablets,inconsistant attendance
Makondo,17,,mobile phones,missing age data,None
Luwero,45,29 mobile phones ; laptops,NaN,None,None
Gulu,,34,tablets,device count unclear,None
Mbale,38,28,mobile phones ; laptops; tablets,good engagement,None

- After loading the messy text data into a DataFrame, we can see that the structure is not perfectly clean.

- Some rows contain missing values, inconsistent formatting, or misplaced data.  

- These types of issues are common in real-world datasets and often require additional data cleaning steps before analysis.

- Despite the messy formatting, Pandas allows us to quickly convert the text data into a structured table that can be explored and cleaned further.

In [ ]:
# Section 1 (ICT4D- Text Data, from the same topic above). 

df = df_raw.copy()

# 1) Clean column names and strip spaces
df.columns = df.columns.str.strip()
for c in df.columns:
    df[c] = df[c].astype(str).str.strip()

# 2) Fix participants and avg age to numeric, coercing errors to NaN
df["participants"] = pd.to_numeric(df["participants"], errors="coerce")
df["avg_age"] = pd.to_numeric(df["avg_age"], errors="coerce")

# Fill missing avg_age with overall mean age (ignoring NaN)
df["avg_age"] = df["avg_age"].fillna(df["avg_age"].mean())

# 3) Basic ICT4D features from device_access text
df["device_access"] = df["device_access"].replace("None", "")
df["has_mobile"] = df["device_access"].str.lower().str.contains("mobile|phone", na=False)
df["has_tablet"] = df["device_access"].str.lower().str.contains("tablet", na=False)
df["has_laptop"] = df["device_access"].str.lower().str.contains("laptop", na=False)

print("Device access counts (how many communities mention each):")
print("Mobile:", df["has_mobile"].sum())
print("Tablet:", df["has_tablet"].sum())
print("Laptop:", df["has_laptop"].sum())

Device access counts (how many communities mention each):
Mobile: 0
Tablet: 1
Laptop: 0

In [75]:
# Now we will view some quick insights based on the cleaned data
print("Top communities by participants:")
display(df.sort_values("participants", ascending=False)[["community", "participants"]])

# Finally, we can also check for any notes that indicate data issues

print("Rows with data issues (based on notes):")
df["notes"] = df["notes"].replace("None", "")
issues = df[df["notes"].str.lower().str.contains("missing|unclear|inconsistent", na=False)]
display(issues[["community", "notes"]])

Top communities by participants:

        community  participants
Gulu                       34.0
Kijiji         23          31.0
Mbale          38          28.0
Makondo        17           NaN
Luwero         45           NaN

Rows with data issues (based on notes):

Empty DataFrame
Columns: [community, notes]
Index: []

In [ ]:
# (Finding three messy datasets). (Additional ICT4D). and provide dataframe with insights of te data

# Dataset 1: Missing Values

data_missing = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Age": [25, None, 30, 35, None],
    "City": ["New York", "London", "Paris", "Tokyo", "Sydney"],
    "Income": [70000, 50000, None, 80000, None],
}

df_missing = pd.DataFrame(data_missing)
print("Dataset with Missing Values:")
display(df_missing)

Dataset with Missing Values:

      Name   Age      City   Income
0    Alice  25.0  New York  70000.0
1      Bob   NaN    London  50000.0
2  Charlie  30.0     Paris      NaN
3    David  35.0     Tokyo  80000.0
4      Eve   NaN    Sydney      NaN

In [77]:
# Simple cleaning: Fill missing ages with average age, and missing income with 0
df_missing["Age"] = df_missing["Age"].fillna(df_missing["Age"].mean())
df_missing["Income"] = df_missing["Income"].fillna(0)

print("Cleaned Dataset:")
display(df_missing)

Cleaned Dataset:

      Name   Age      City   Income
0    Alice  25.0  New York  70000.0
1      Bob  30.0    London  50000.0
2  Charlie  30.0     Paris      0.0
3    David  35.0     Tokyo  80000.0
4      Eve  30.0    Sydney      0.0

- Dataset 1 contained missing values in the age, city, and income columns.
- Missing ages were replaced with the average age and missing income values were filled with 0.

In [78]:
# For the second dataset we will create, we will deal with Inconsistent Formatting

data2 = {
    "product": ["Laptop", "laptop", "LAPTOP", "Tablet", "tablet"],
    "price": [1200, 1200, 1200, 300, 800],
    "quantity": [5, 5, 5, 10, 10]
}

df2 = pd.DataFrame(data2)
print("Dataset with Inconsistent Formatting:")  
display(df2)

Dataset with Inconsistent Formatting:

  product  price  quantity
0  Laptop   1200         5
1  laptop   1200         5
2  LAPTOP   1200         5
3  Tablet    300        10
4  tablet    800        10

In [79]:
# So now we will clean the product names to be consistent (e.g., all lowercase)

df2["product"] = df2["product"].str.strip().str.lower()

product_summary = df2.groupby("product").agg(
    total_quantity=("quantity", "sum"),
    total_revenue=("price", "sum")
)

print("Product Summary after Cleaning:")
display(product_summary)

Product Summary after Cleaning:

         total_quantity  total_revenue
product
laptop               15           3600
tablet               20           1100

- The dataset contained inconsistent formatting for product names.
- By cleaning the text and converting it to lowercase, duplicate categories were merged correctly.

In [80]:
# For the last dataset, we will create one with mixed data types

data_mixed = {
    "student": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "score": [85, "N/A", 92, 88, "N/A"],
    "attendance": [True, False, True, True, None]   
}

df_mixed = pd.DataFrame(data_mixed)
print("Dataset with Mixed Data Types:")
display(df_mixed)

Dataset with Mixed Data Types:

   student score attendance
0    Alice    85       True
1      Bob   N/A      False
2  Charlie    92       True
3    David    88       True
4      Eve   N/A       None

In [81]:
# As you can see, students like Eve and Bob have "N/A" for their scores, which is a string instead of a numeric value. We will convert these to NaN and then fill them with the average score.

# Fix Score Coloumn
df_mixed["score"] = pd.to_numeric(df_mixed["score"], errors="coerce")

# Fill missing attendance
df_mixed["attendance"] = df_mixed["attendance"].fillna(df_mixed["attendance"].mean())

print("Dataset with Mixed Data Types (after cleaning):")
display(df_mixed)

Dataset with Mixed Data Types (after cleaning):

   student  score attendance
0    Alice   85.0       True
1      Bob    NaN      False
2  Charlie   92.0       True
3    David   88.0       True
4      Eve    NaN       0.75

### Observations

- The dataset originally contained mixed data types where numeric values were stored as text ("N/A").
- Using `pd.to_numeric()` converted these values into proper numeric format, while invalid values became NaN.

- Missing attendance values were filled using the average attendance value.